name: Build Executable from latest `arcaea-offline-*` dependencies
run-name: ${{ github.actor }} started a build request.

on:
  workflow_dispatch:

permissions:
  contents: write
  discussions: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # install dependencies
      - run: "pip install -r requirements.txt"
      - run: "pip uninstall arcaea-offline arcaea-offline-ocr -y"
      - run: "pip install git+https://github.com/283375/arcaea-offline"
      - run: "pip install git+https://github.com/283375/arcaea-offline-ocr"
      - run: "pip install imageio"
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: Release builtin files
        run: |
          pyside6-lrelease ui/resources/lang/en_US.ts ui/resources/lang/zh_CN.ts
          python prebuild.py
          pyside6-rcc ui/resources/resources.qrc -o ui/resources/resources_rc.py

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: index.py
          standalone: true
          onefile: true
          enable-plugins: pyside6,upx
          windows-icon-from-ico: ui/resources/images/icon.png
          linux-icon: ui/resources/images/icon.png

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
